# Generated by Django 3.2.24 on 2025-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('technician', models.CharField(max_length=30, null=True)),
                ('machine', models.CharField(max_length=30, null=True)),
                ('sparePart', models.CharField(max_length=30, null=True)),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField(null=True)),
                ('connections', models.TextField(null=True)),
                ('nodes', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('supplier', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('sparePart', models.ManyToManyField(related_name='machine_categories', to='map.SparePart')),
            ],
        ),
    ]
