# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
