# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170918_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='connections',
            field=models.TextField(null=True),
        ),
    ]
