# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_process_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='nodes',
            field=models.TextField(null=True),
        ),
    ]
