# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_process_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Spare_part',
            new_name='SparePart',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MachineCategory'),
        ),
        migrations.AddField(
            model_name='machinecategory',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.SparePart'),
        ),
        migrations.AddField(
            model_name='machinecategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Supplier'),
        ),
    ]
