# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20170924_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecategory',
            name='spare_part',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='supplier',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
