# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20170924_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='qty',
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.SparePart'),
        ),
    ]
