# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20171009_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='machine',
        ),
    ]
