# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_sparepart_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecategory',
            name='spare_part',
        ),
        migrations.AddField(
            model_name='machinecategory',
            name='spare_part',
            field=models.ManyToManyField(to='map.SparePart'),
        ),
    ]
