# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20171011_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinecategory',
            old_name='spare_part',
            new_name='sparePart',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='spare_part',
            new_name='sparePart',
        ),
    ]
