# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20171011_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='id',
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='sparePart',
            field=models.ManyToManyField(related_name='SparePart', to='map.SparePart'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
