# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20171011_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecategory',
            name='sparePart',
        ),
        migrations.AddField(
            model_name='machinecategory',
            name='sparepart',
            field=models.ManyToManyField(to='map.SparePart'),
        ),
    ]
